import type { VehicleFormData } from "@/lib/schemas/vehicle";

export const demoVehicleInput: VehicleFormData = {
  brand: "Toyota",
  model: "Corolla",
  year: 2020,
  trim: "Dream",
  fuelType: "Benzin",
  transmission: "Otomatik",
  mileage: 90000,
  price: 1200000,
  city: "İstanbul",
  bodyType: "Sedan",
  engineSize: "1.6",
  enginePower: "132",
  drivetrain: "Önden çekiş",
  ownerInfo: "Ruhsat sahibi satıcı olduğunu belirtiyor",
  tradeStatus: "Takas yok",
  tramerAmount: 75000,
  paintedParts: "Sağ ön çamurluk",
  replacedParts: "",
  localPaintedParts: "Ön tampon",
  hasHeavyDamage: false,
  hasChassisRepair: false,
  airbagStatus: "Açmamış",
  hasTotalLossHistory: false,
  hasExpertiseReport: true,
  lastMaintenanceDate: "2026-03-15",
  timingBeltInfo: "Bilinmiyor",
  transmissionMaintenanceInfo: "Bakım yapılmış, belge yok",
  batteryStatus: "İyi",
  tireStatus: "Orta",
  inspectionEndDate: "2026-12-20",
  lpgStatus: "Yok",
  lpgRegistered: false,
  hasSpareKey: true,
  hasMaintenanceInvoices: true,
  sellerDescription:
    "Ekspertize açık, kapalı garajda durdu, tramer yok, masrafsız yazılmış ama tramer detayını ve bakım belgelerini görmek istiyorum.",
  listingUrl: "https://example.com/anonim-ilan",
};
